(function(c,a){var b=a.cookie("region_name");if(b){a("#DY_site_name").html(b.slice(0,4)+"站");if(b.slice(0,4)=="广州"){jQuery("#JS_mll_head_menu_dz").html('<a target="_blank" title="定制家居" href="http://dz.meilele.com/">定制家居<img src="http://image.meilele.com/images/new2015.gif" /></a>').show();
}}})(document,jQuery);(function(a){jQuery.fn.menu=function(c){this.each(function(){b.call(this,c);});return this;};function b(o){var h=a(this),k=null,f=[],j=null,i=null,r=null,e=a.extend({rowSelector:"> li",submenuSelector:"*",submenuDirection:"right",tolerance:75,enter:a.noop,exit:a.noop,activate:a.noop,deactivate:a.noop,exitMenu:a.noop,firstDelay:0},o);
var c=3,m=300,l=0;var g=function(w){f.push({x:w.pageX,y:w.pageY});if(f.length>c){f.shift();}};var n=function(){clearTimeout(r);if(i){clearTimeout(i);}if(e.exitMenu(this)){if(k){e.deactivate(k);
}}k=null;};var q=function(){(!k)&&clearTimeout(r);};var t=function(w){if(i){clearTimeout(i);}e.enter(this);s(this);},p=function(w){e.exit(this);};var u=function(w){d(this);
w.stopPropagation();};var d=function(x){clearTimeout(r);if(k){e.deactivate(k);}if(!k&&e.firstDelay){r=setTimeout(function(){w(x);},e.firstDelay);}else{w(x);
}function w(y){e.activate(y);k=y;}};var s=function(x){var w=v();if(w){i=setTimeout(function(){s(x);},w);}else{d(x);}};var v=function(){if(!k||!a(k).is(e.submenuSelector)){return 0;
}var A=h.offset(),w={x:A.left,y:A.top-e.tolerance},H={x:A.left+h.outerWidth(),y:w.y},J={x:A.left,y:A.top+h.outerHeight()+e.tolerance},B={x:A.left+h.outerWidth(),y:J.y},C=f[f.length-1],G=f[0];
if(!C){return 0;}if(!G){G=C;}if(G.x<A.left||G.x>B.x||G.y<A.top||G.y>B.y){return 0;}if(j&&C.x==j.x&&C.y==j.y){return 0;}function D(L,K){return(K.y-L.y)/(K.x-L.x);
}var F=H,x=B;if(e.submenuDirection=="left"){F=J;x=w;}else{if(e.submenuDirection=="below"){F=B;x=J;}else{if(e.submenuDirection=="above"){F=w;x=H;}}}var y=D(C,F),E=D(C,x),I=D(G,F),z=D(G,x);
if(y<I&&E>z){j=C;return m;}j=null;return 0;};h.on("mouseleave",n).on("enter",q).find(e.rowSelector).on("mouseenter",t).on("mouseleave",p).on("click",u);
a(document).mousemove(g);}})(jQuery);function _INIT_HEAD_SEARCH(data){var json;try{json=eval(data.html_content);}catch(e){}if(json&&json.length){var url=location.pathname;
var wordIndex=-1;var tmpFilter;window.__HEAD_SEARCH_WORDS_ARR=[];window.__HEAD_SEARCH_WORDS_OBJ={};if(/\/jiaju\//.test(url)){wordIndex=0;}else{if(/\/jiancai\//.test(url)){wordIndex=1;
}else{if(/\/shipin\//.test(url)){wordIndex=2;}}}for(var k=0,kk=json.length;k<kk;k++){tmpFilter=json[k].type.split("");if(wordIndex==-1||tmpFilter[wordIndex]==1){__HEAD_SEARCH_WORDS_ARR.push(json[k]);
__HEAD_SEARCH_WORDS_OBJ[json[k].text]=json[k];}}var inpt=$("#JS_MLL_search_header_input")[0];var inpt2=$("#JS_MLL_search_fixed_input")[0];if(__HEAD_SEARCH_WORDS_ARR.length&&inpt&&inpt.value==""){inpt.value=MLL_Header_search_words();
inpt.setAttribute("data-sug","none");inpt.onfocus=function(){this.value="";this.onfocus=function(){};};inpt.onblur=function(){if(this.value==""){inpt.setAttribute("data-sug","none");
this.value=MLL_Header_search_words();this.onfocus=function(){this.value="";this.onfocus=function(){};};}};}if(__HEAD_SEARCH_WORDS_ARR.length&&inpt2&&inpt2.value==""){inpt2.value=MLL_Header_search_words();
inpt2.setAttribute("data-sug","none");inpt2.onfocus=function(){this.value="";this.onfocus=function(){};};inpt2.onblur=function(){if(this.value==""){inpt2.setAttribute("data-sug","none");
this.value=MLL_Header_search_words();this.onfocus=function(){this.value="";this.onfocus=function(){};};}};}}}function MLL_header_search_submit(d){var h="";
var c=$("#JS_MLL_search_header_input")[0];var f=$("#JS_search_form")[0];var b=$("#JS_MLL_search_fixed_input")[0];if(d){h=b.value+"";}else{h=c.value+"";
}h=$.trim(h||"");var e=h;if(h&&e.replace(/[^\x00-\xff]/g,"**").length<31){var g=$.cookie("search_h");if(g){g=unescape(g);g=g.split("*#");g=a(g,h);if(g.length>9){g.shift();
}g=g.join("*#");g+="*#"+h;}else{g=h+"*#";}g=escape(g);$.cookie("search_h",g,{path:"/",expires:30});}function a(j,m){var l=[];for(var k=0;k<j.length;k++){if(j[k]!=m){l.push(j[k]);
}}return l;}if(!h){return false;}if(d){if(window._ana){window._ana.push(["trackEvent","jjc_xfss","click","点击悬浮搜索框"]);}}if(window.__HEAD_SEARCH_WORDS_OBJ&&__HEAD_SEARCH_WORDS_OBJ[h]){window.open(__HEAD_SEARCH_WORDS_OBJ[h].href+(__HEAD_SEARCH_WORDS_OBJ[h].href.indexOf("#")>=0?"&":"#")+"kw="+encodeURIComponent(h));
return false;}else{if(d){b.value=h;}else{c.value=h;}return true;}}function menuEvent(){var c=$("#JS_mll_menu_map"),b=$("#JS_mll_menu_map_fix");var a={activate:function(f){var g=$(f);
if(!g.data("imgLoaded")){var e=g.find(".sub img");e.prop("src",e.attr("menu-lazy-src")).removeAttr("menu-lazy-src");g.data("imgLoaded",1);}g.addClass("hover").find(".sub").stop().animate({"padding-left":"10px",opacity:"1"},200);
if(window._ana){window._ana.push(["trackEvent","jjc_zcdhnew","mouseover","新家具城菜单鼠标移入"]);}if(window._gaq){window._gaq.push(["_trackEvent","jjc_zcdhnew","mouseover","新家具城菜单鼠标移入"]);
}var d=!-[1,]&&!window.XMLHttpRequest;if(d){if(g.hasClass("large-class")){c.css("width","975px");}else{c.css("width","845px");}}},deactivate:function(d){var e=$(d);
e.removeClass("hover").find(".sub").stop().animate({"padding-left":0,opacity:".8"},200);},rowSelector:"li.map-item",exitMenu:function(g){var g=$(g);var f=g.find(".hover");
var d=f.find(".sub");f.find("em").stop().animate({"padding-left":0,opacity:0},200);f.removeClass("hover");var e=!-[1,]&&!window.XMLHttpRequest;if(e){c.css("width","200px");
}},firstDelay:100};c.menu(a);b.menu(a);if(!_ipad_from){$("#JS_menu_fix_btn").hover(function(){b.addClass("menu-map-hover");},function(){window._fixMenuTimer=setTimeout(function(){b.removeClass("menu-map-hover");
},1500);});b.hover(function(){if(_fixMenuTimer){clearTimeout(window._fixMenuTimer);}if(!b.hasClass("menu-map-hover")){b.addClass("menu-map-hover");}},function(){b.removeClass("menu-map-hover");
});}else{$("#JS_menu_fix_btn").click(function(){if(b.hasClass("menu-map-hover")){b.removeClass("menu-map-hover");}else{b.addClass("menu-map-hover");}});
}}var AutoPlay=function(){this.initialize();};AutoPlay.prototype={initialize:function(){var b=this;this.oBox=$("#JS_mll_scroll_bar");this.oUl=$("#JS_mll_scroll_bar .scroll-content");
this.oLi=$("#JS_mll_scroll_bar .scroll-item");this.timer=null;this.autoTimer=null;this.iNow=0;this.aBtn=$("#JS_mll_scroll_bar .scroll-btn span");this.autoTimer=setInterval(function(){b.next();
},4000);this.oBox.mouseenter(function(){clearInterval(b.autoTimer);});this.oBox.mouseleave(function(){b.autoTimer=setInterval(function(){b.next();},4000);
});for(var a=0;a<this.aBtn.length;a++){this.aBtn[a].index=a;this.aBtn[a].onmouseover=function(){if(this.index==b.iNow){return;}b.iNow=this.index;b.toggle();
};}},toggle:function(){for(var a=0;a<this.aBtn.length;a++){this.aBtn[a].className="";}this.aBtn[this.iNow].className="current";this.lazy(this.iNow);this.doShow(this.iNow);
},next:function(){var a=this;this.iNow++;this.iNow==this.aBtn.length&&(this.iNow=0);this.toggle();},lazy:function(b){var a=this.oLi.eq(b);if(!a.data("imgLoaded")){a.find("img").each(function(){jQuery(this).prop("src",$(this).attr("lazy-src")).removeAttr("lazy-src");
});a.data("imgLoaded",1);}},doShow:function(a){var b=this;b.oLi.addClass("none");b.oLi.fadeOut(500);b.oLi.eq(a).fadeIn(500);}};function actFloor(){var c={};
b();a();setInterval(function(){for(var d in c){if(typeof d!="function"){if(c[d].obj.actTimer){clearInterval(c[d].obj.actTimer);}if(c[d].obj[c[d].type+"UnixtimeGoods"]){c[d].obj[c[d].type+"UnixtimeGoods"].call(c[d].obj);
}else{c[d].obj.usualUnixtimeGoods();}}}},60000);function b(g){var f=$(".activity-floor .JS_act_bk"),e=[],d={};f.each(function(){e.push($(this).data("goodsid"));
d[$(this).data("goodsid")]=$(this);});if(!e.length){return;}$.ajax({url:"/mll_api/api/goods_actbonus?goods_id="+e.join("*"),dataType:"json",cache:false,success:function(h){if(h){if(e.length>1){for(var i in h){if(typeof i!="function"){c[i]={type:"bk"};
c[i].obj=new ActItem(d[i],(h[i]&&h[i].error==0)?{start:h[i].data.act.start,end:h[i].data.act.end}:null);}}}else{if(h.error==0){c[e[0]]={type:"bk"};c[e[0]].obj=new ActItem(f,h.error==0?{start:h.data.act.start,end:h.data.act.end}:null);
}}}}});}function a(){var j={},d=[],e=[],h,i;$(".activity-floor .JS_act_item").each(function(){h=$(this).data("acttype");i=$(this).data("actid");i=(i&&i!="0")?i:$(this).data("goodsid");
if(h!="bk"){j[h]=j[h]||[];j[h].push(i);e.push({id:i,type:h,dom:$(this)});}});for(var f in j){if(typeof f!="function"){d.push('"'+f+'":"'+j[f].join("*")+'"');
}}if(!d.length){return;}d=encodeURIComponent("{"+d.join(",")+"}");var g=this;$.ajax({url:"/mll_api/api/act_goods_info?goods_act="+d,dataType:"json",cache:false,success:function(m){if(m){for(var l in e){var n=e[l];
c[n.id]={type:n.type};c[n.id].obj=new ActItem(n.dom,(m[n.type]&&m[n.type][n.id])?m[n.type][n.id]:null);}}}});}}var ActItem=function(a,b){this.actDom=a;
this.info=b;this.actType=a.data("acttype");this.goodsId=a.data("goodsid");this.actBtn=a.find(".JS_act_btn");this.effpriceDom=a.find(".JS_effect_price");
this.delpriceDom=a.find(".JS_del_price");this.actDescDom=a.find(".JS_act_desc");this.timeDescDom=a.find(".JS_time_desc");this.timeCountDom=a.find(".JS_time_count");
this.actid=a.data("actid");this.actid=this.actid&&this.actid!="0"?this.actid:this.goodsId;this.timeHtml='<span class="time">$H</span>:<span class="time">$M</span>:<span class="time">$S</span>';
this.initAct();};ActItem.prototype={constructor:ActItem,initAct:function(){if(this.info){this.info.current_time=this.info.current_time||parseInt(new Date/1000);
this.info.diffTime=parseInt(new Date().getTime()/1000)-parseInt(this.info.current_time);if(this[this.actType+"BtnEvent"]){this[this.actType+"BtnEvent"].call(this);
this[this.actType+"UnixtimeGoods"].call(this);}else{this.usualBtnEvent.call(this);this.usualUnixtimeGoods.call(this);}}else{if(!this[this.actType+"BtnEvent"]){this.usualBtnEvent.call(this);
}this.info={};this.timeDescDom.text("距结束");this.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");this.timeCountDom.html(this.timeHtml.replace("$H","00").replace("$M","00").replace("$S","00"));
}},refresh:function(){var a=this.actType,d=this.actid,b='{"'+a+'":"'+d+'"}',c=this;$.ajax({url:"/mll_api/api/act_goods_info?goods_act="+encodeURIComponent(b),dataType:"json",cache:false,success:function(e){if(e&&e[a]&&e[a][d]){var f=e[a][d];
if(c.actTimer){clearInterval(c.actTimer);}if(f){c.info=f;c.info.diffTime=parseInt(new Date().getTime()/1000)-parseInt(c.info.current_time)-1;if(c[c.actType+"UnixtimeGoods"]){c[c.actType+"UnixtimeGoods"].call(c);
}else{c.usualUnixtimeGoods.call(c);}}else{c.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");c.timeCountDom.html(c.timeHtml.replace("$H","00").replace("$M","00").replace("$S","00"));
}}}});},usualBtnEvent:function(){this.actDom.on("click",".JS_act_btn",function(){window.open($(this).data("url"));return false;});},bkBtnEvent:function(){var a=this;
this.actDom.on("click",".JS_bk_tx",function(){$.ajax({url:"/mll_api/api/goods_actbonus?goods_id="+a.goodsId,type:"get",success:function(b){if(b&&b.data.act_id){$.sendActGoods(null,{chooseExpr:false,isNeedImgChap:"1",type:"get_bk_tx",unique:b.data.act_id,click:"家具城爆款特惠订阅",prize_id:b.data.act_id+"_"+a.goodsId});
}},error:function(){alert("数据连接失败，请重试！");}});}).on("click",".JS_bk_kq",function(){$.ajax({url:"/mll_api/api/goods_actbonus?goods_id="+a.goodsId,type:"get",success:function(c){if(c&&c.data.act_id){var b=new Date(c.data.start*1000),d=new Date(c.data.end*1000);
b=b.getFullYear()+"."+(b.getMonth()+1)+"."+b.getDate();d=d.getFullYear()+"."+(d.getMonth()+1)+"."+d.getDate();$.customBoxExtend({type:"get_limited_prize_goods",unique:c.data.act_id,prize_id:c.data.act_id+"_"+a.goodsId,marginW:true,click:"jjc_yhq"});
}},error:function(){alert("数据连接失败，请重试！");}});});},pmBtnEvent:function(){var a=this;this.actDom.on("click",".JS_pm_now",function(){var b=$(this).data("url");
window.open(b);return false;}).on("click",".JS_pm_bm",function(){$.sendActGoods(null,{type:"get_pm_bm",prize_id:a.actid,click:"家具城拍卖订阅",extSendSucCB:function(){a.refresh();
}});});},tgBtnEvent:function(){var a=this;this.actDom.on("click",".JS_tg_bm",function(){$.sendActGoods(null,{chooseExpr:false,checkPhone:true,notice:"<b>温馨提示：</b>最终团购价以活动开始后的价格为准，该价格不能享受满减和红包优惠。",type:"get_tg_bm",captcha_type:"tg_baoming",prize_id:a.actid,click:"家具城团购订阅",extSendSucCB:function(){a.refresh();
}});}).on("click",".JS_tg_tx",function(){$.customBoxExtend({type:"tg_sign_up",goodsId:a.actid,marginW:true,extSendSucCB:function(){a.refresh();},click:"jjc_lft"});
}).on("click",".JS_tg_now",function(){var b=$(this).data("url");window.open(b);return false;});},msBtnEvent:function(){var a=this;this.actDom.on("click",".JS_ms_todetail",function(){window.open($(this).data("url"));
return false;}).on("click",".JS_ms_bm",function(){if(!$.cookie("ECS[username]")||$.cookie("meilele_login")!="1"){$.showLoginBox(function(){location.reload();
});}else{$.customBoxExtend({type:"ms_sign_up",act_id:a.actid,extSendSucCB:function(){a.refresh();},marginW:true,click:"jjc_djms"});}}).on("click",".JS_ms_now",function(){var b=$(this);
if(b.hasClass("click-submit")){return;}b.addClass("click-submit");if(!$.cookie("ECS[username]")||$.cookie("meilele_login")!="1"){$.showLoginBox(function(){location.reload();
});}else{$.ajax({url:"/dispose/?act=start_buy&id="+a.actid,type:"GET",dataType:"json",success:function(c){if(c){if(c.error===0){var d=$('<form action="/action-sec_buy-'+a.actid+'.html" method="post" target="_self"><input type="hidden" name="check_key" value="'+c.msg+'"></form>');
d.appendTo($("body"));d[0].submit();d.remove();}else{if(c.error==2){$.alert(c.msg+'<br/>点击参与<a href="'+c.url+'" class="orange">下期秒杀</a>吧',{onOk:function(){window.location.href=c.url;
}});}else{if(c.error==1&&c.flag){if(c.flag=="waiting"){$.alert(c.msg);}else{$.cookie("meilele_login","");}}else{if(c.future==1){$.alert(c.msg+'<br/>点击参与<a href="/miaosha/future.html" class="orange">下期秒杀</a>吧');
}else{$.alert(c.msg);}}}}}},complete:function(){b.removeClass("click-submit");}});}});},usualUnixtimeGoods:function(){var a=this;this.info.current_time=parseInt(new Date/1000)-this.info.diffTime;
this.info.leftTimeTopic=this.info.start_time-this.info.current_time;if(!this.info.start_time||this.info.leftTimeTopic<=0){this.timeDescDom.text("距结束");
this.info.leftTimeTopic=this.info.end_time-this.info.current_time;this.interval.call(this);}else{this.info.leftTimeTopic--;this.interval.call(this,this.usualUnixtimeGoods);
}},bkUnixtimeGoods:function(){var b=new Date().getTime(),a=this;this.info.leftTimeTopic=parseInt(this.info.start-b/1000);if(this.info.leftTimeTopic<=0){this.timeDescDom.text("距结束");
this.actBtn.text("立即领取").removeClass("JS_bk_tx").addClass("JS_bk_kq");this.info.leftTimeTopic=parseInt(this.info.end-b/1000);this.interval.call(this);}else{this.actBtn.text("开抢提醒").addClass("JS_bk_tx");
this.info.leftTimeTopic--;this.interval.call(this,function(){a.timeDescDom.text("距结束");a.actBtn.text("立即领取").removeClass("JS_bk_tx").addClass("JS_bk_kq");
a.info.leftTimeTopic=parseInt(a.info.end-a.info.start)-1;a.interval.call(a);});}},pmUnixtimeGoods:function(){var a=this;this.effpriceDom.html("&yen;"+this.info.current_price);
this.delpriceDom.html("&yen;"+this.info.shop_price);this.info.current_time=parseInt(new Date().getTime()/1000)-this.info.diffTime;if(this.info.h_is_Forbid=="1"||this.info.auction_status=="3"){this.timeDescDom.text("距结束");
this.actDescDom.text("已竞价"+this.info.h_auction_log_num+"次");this.actBtn.text("已结束").addClass("act-disable").prev().addClass("disable");}else{if(this.info.auction_status==2){this.info.leftTimeTopic=parseInt(this.info.start_time)-this.info.current_time-1;
this.effpriceDom.html("&yen;"+this.info.start_price+'<span class="gray">(起拍价)</span>');this.actBtn.text("我要报名").addClass("JS_pm_bm");this.actDescDom.text("已报名"+this.info.h_auction_user_num+"人");
this.interval.call(this,function(){a.info.leftTimeTopic=parseInt(a.info.end_time)-parseInt(a.info.start_time);a.timeDescDom.text("距结束");a.actDescDom.text("已竞价"+a.info.h_auction_log_num+"次");
a.actBtn.text("竞价中").attr("class","act-btn JS_pm_now");a.interval.call(a);});}else{if(this.info.auction_status==1){this.info.leftTimeTopic=parseInt(this.info.end_time)-this.info.current_time-1;
this.timeDescDom.text("距结束");this.actDescDom.text("已竞价"+this.info.h_auction_log_num+"次");this.actBtn.text("竞价中").attr("class","act-btn JS_pm_now");this.interval.call(this);
}}}},tgUnixtimeGoods:function(){var a=this;this.effpriceDom.html("&yen;"+this.info.min_price);this.delpriceDom.html("&yen;"+this.info.h_shop_price);this.info.current_time=parseInt(new Date().getTime()/1000)-this.info.diffTime;
this.info.leftTimeTopic=parseInt(this.info.start_time)-this.info.current_time;if(this.info.h_is_Forbid==1||this.info.h_is_on_sale!="1"){this.timeDescDom.text("距结束");
this.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");}else{if(this.info.left_number<=0){this.timeDescDom.text("距结束");
this.actBtn.text("已售完").attr("class","act-btn act-disable").prev().addClass("disable");}else{if(this.info.leftTimeTopic>0){if(this.info.is_need_apply==1){this.actBtn.text("我要报名").addClass("JS_tg_bm");
}else{this.actBtn.text("开团通知").addClass("JS_tg_tx");}this.interval.call(this,function(){a.timeDescDom.text("距结束");a.actBtn.text("立即参团").attr("class","act-btn JS_tg_now");
a.info.leftTimeTopic=parseInt(a.info.end_time)-parseInt(a.info.start_time);a.interval.call(a);});}else{this.info.leftTimeTopic=parseInt(this.info.end_time)-this.info.current_time-1;
if(this.info.leftTimeTopic<=0){this.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");this.timeCountDom.html(this.timeHtml.replace("$H","00").replace("$M","00").replace("$S","00"));
}else{this.timeDescDom.text("距结束");this.actBtn.text("立即参团").attr("class","act-btn JS_tg_now");this.interval.call(this);}}}}},msUnixtimeGoods:function(){var a=this;
this.effpriceDom.html("&yen;"+this.info.max_price);this.delpriceDom.html("&yen;"+this.info.shop_price);this.actDescDom.html("已报名"+this.info.join_count+"人");
this.info.current_time=parseInt(new Date().getTime()/1000)-this.info.diffTime;var b=this.info.bstatus;if(b==6||b==5||this.info.h_is_Forbid==1){this.timeDescDom.text("距结束");
this.actBtn.text("已结束").addClass("act-disable").prev().addClass("disable");}else{if(b==2){this.actBtn.text("未开始").addClass("JS_ms_todetail").removeClass("JS_ms_bm");
this.info.leftTimeTopic=parseInt(this.info.starttime)-this.info.current_time-1;this.interval.call(this,function(){a.info.leftTimeTopic=parseInt(a.info.endtime)-parseInt(a.info.starttime);
a.timeDescDom.text("距结束");a.actBtn.text("马上秒杀").removeClass("JS_ms_todetail").addClass("JS_ms_now");a.interval.call(a);});}else{if(b==1){this.actBtn.text("报名参与").addClass("JS_ms_bm");
this.info.leftTimeTopic=parseInt(this.info.starttime)-this.info.current_time-1;if(this.info.leftTimeTopic<=0){this.timeDescDom.text("距结束");this.info.leftTimeTopic=+this.info.remain_time;
this.interval.call(this);}else{this.interval.call(this,function(){a.info.leftTimeTopic=parseInt(a.info.endtime)-parseInt(a.info.starttime);a.timeDescDom.text("距结束");
if(a.info.bstatus==3){a.actBtn.text("马上秒杀").removeClass("JS_ms_bm").addClass("JS_ms_now");}a.interval.call(a);});}}else{if(b==3||b==4){this.timeDescDom.text("距结束");
this.info.leftTimeTopic=parseInt(this.info.endtime)-this.info.current_time-1;this.actBtn.text("马上秒杀").addClass("JS_ms_now");this.interval.call(this);}}}}},interval:function(b){var a=this;
if(this.actTimer){clearInterval(this.actTimer);}if(isNaN(a.info.leftTimeTopic)){this.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");
this.timeCountDom.html(this.timeHtml.replace("$H","00").replace("$M","00").replace("$S","00"));return;}this.actTimer=setInterval(function(){if(a.info.leftTimeTopic<=0){clearInterval(a.actTimer);
if(b&&typeof b=="function"){b.call(a);}else{a.actBtn.text("已结束").attr("class","act-btn act-disable JS_act_btn").prev().addClass("disable");a.timeCountDom.html(a.timeHtml.replace("$H","00").replace("$M","00").replace("$S","00"));
}return;}var f=a.info.leftTimeTopic;var e=f%60;if(e<10){e="0"+e;}var c=parseInt(f%3600/60);if(c<10){c="0"+c;}var d=parseInt(f/3600);a.timeCountDom.html(a.timeHtml.replace("$H",d).replace("$M",c).replace("$S",e));
a.info.leftTimeTopic--;},1000);}};function initFloors(){$(".JS_floor_banner").each(function(a){var b=new floor_slide({content:$(this).find(".content"),li:$(this).find(".JS_ul_banner li"),nav:$(this).find(".JS_list_banner a"),prev:$(this).find(".prev"),next:$(this).find(".next"),divbox:$(this),img:$(this).find(".JS_ul_banner li img")});
b.init(0);});}function floor_slide(a){this.main=a.main,this.content=a.content;this.Li=a.li;this.num=this.Li.length;this.nav=a.nav;this.prev=a.prev;this.next=a.next;
this.banCont=a.divbox;this.timer=null;this.imgs=a.img;this.init=function(b){this.column(b);this.addEve();this.clickNavE();};this.column=function(b){var c=this;
c.focusImg(b);c.navE(b);c.timer=setInterval(function(){if(c.floorSlideLock){return;}b++;if(b>c.num-1){b=0;}c.focusImg(b);c.navE(b);c.lazyImg(b);},4000);
};this.focusImg=function(b){var f=!-[1,];var e=this;if(e.main){jQuery("#JS_mll_scroll_bar").css("background","#"+e.Li.eq(b).data("bgcolor"));}for(var c=0,d=e.num;
c<d;c++){if(f){e.Li.eq(c).css({opacity:0,zIndex:0}).addClass("none");}else{e.Li.eq(c).animate({opacity:0},200,function(){jQuery(this).css("zIndex",0).addClass("none");
});}if(e.content){if(f){e.content.eq(c).css("opacity",0).addClass("none");}else{e.content.eq(c).animate({opacity:0},200,function(){jQuery(this).addClass("none");
});}}}e.Li.eq(b).removeClass("none");e.Li.eq(b).css("zIndex",2);if(e.content){e.content.eq(b).removeClass("none");if(f){e.content.eq(b).css("opacity",1);
}else{e.content.eq(b).stop(true).animate({opacity:1},200);}}if(f){e.Li.eq(b).css("opacity",1);}else{e.Li.eq(b).stop(true).animate({opacity:1},200);}};this.navE=function(b){this.nav.each(function(){jQuery(this).removeClass("hover");
});this.nav.eq(b).addClass("hover");};this.clickNavE=function(){var b=this;if(this.prev.length){this.banCont.hover(function(){b.prev.show();b.next.show();
},function(){b.prev.hide();b.next.hide();});}this.prev.click(function(){var c=0;b.nav.each(function(){if(jQuery(this).hasClass("hover")){c=jQuery(this).index();
}});if(c==0){c=b.num-1;}else{c-=1;}b.focusImg(c);b.navE(c);if(window._ana){window._ana.push(["trackEvent","jjc_fglc","click","家具城楼层大图切换"]);}if(window._gaq){window._gaq.push(["_trackEvent","jjc_fglc","click","家具城楼层大图切换"]);
}return false;});this.next.click(function(){var c=0;b.nav.each(function(){if(jQuery(this).hasClass("hover")){c=jQuery(this).index();}});if(c==b.num-1){c=0;
}else{c+=1;}b.focusImg(c);b.navE(c);if(window._ana){window._ana.push(["trackEvent","jjc_fglc","click","家具城楼层大图切换"]);}if(window._gaq){window._gaq.push(["_trackEvent","jjc_fglc","click","家具城楼层大图切换"]);
}return false;});};this.delay=function(e,f){var c=0,b=10,e=(e*1000)/b,h=this,g=setInterval(function(){c++;if(c==b){clearInterval(g);f.apply(h);}},e);h.onmouseout=function(){clearInterval(g);
};};this.lazyImg=function(c){var b=this.imgs.eq(c).attr("lazy-src");if(this.main){var d=this.imgs.eq(c).next().attr("lazy-src");this.imgs.next().eq(c).attr("src",d).removeAttr("lazy-src");
}if(b){this.imgs.eq(c).attr("src",b).removeAttr("lazy-src");}};this.addEve=function(){var b=this;b.nav.each(function(c){jQuery(this).on("mouseover",function(){if(!window.VBArray){b.delay.apply(this,[0.18,function(){b.navE();
$(this).addClass("hover");if($(this).hasClass("hover")){b.focusImg(c);b.lazyImg(c);}}]);}else{b.navE();$(this).addClass("hover");if($(this).hasClass("hover")){b.focusImg(c);
b.lazyImg(c);}}});});b.banCont.on({mouseover:function(){b.floorSlideLock=true;},mouseout:function(){b.floorSlideLock=false;}});};}function arrayFilter(a,d){var c;
for(var b in a){if(typeof b!="function"){if(d<a[b]){c=b;break;}}}return c||99;}function stairs_show(){var a=document.body.clientWidth,e=window.LOAD?1460:1190,d=a-e,b=jQuery(window).height();
if(d<160){jQuery("#JS_default_stairs").addClass("none");}else{jQuery("#JS_default_stairs").removeClass("none");}if(b>550){jQuery(".default_stairs_w").css("top",(b-500)/2+"px");
}}function stairs_move(){var a=$("#JS_default_stairs"),b=a.find("a"),d=true,c=[];$(".JS_floor").each(function(e){c.push(Math.ceil($(this).offset().top-200));
});c.push(c[c.length-1]+500);$(window).on("scroll",function(){var f=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;
a.removeClass("out");if(f>=600){if(!-[1,]){a.show();}else{a.css({transform:"scale(1)",opacity:1});}a.find(".stairs-cover").addClass("none");stairs_show();
}else{if(!-[1,]){a.hide();}else{a.css({transform:"scale(1.2)",opacity:0});}a.find(".stairs-cover").removeClass("none");}var e=arrayFilter(c,f);if(e==undefined){if(!-[1,]){a.hide();
}else{a.css({transform:"scale(1.2)",opacity:0});}a.find(".stairs-cover").removeClass("none");}b.each(function(){jQuery(this).removeClass("current");});
if(e<1){b.eq(0).addClass("current");}else{b.eq(e-1).addClass("current");}});a.on("mouseover","a",function(){jQuery(this).addClass("hover");}).on("mouseout","a",function(){jQuery(this).removeClass("hover");
}).on("click","a",function(){if(window._ana){window._ana.push(["trackEvent","jjc_zclcdh","click","家具城左导航点击"]);}if(window._gaq){window._gaq.push(["_trackEvent","jjc_zclcdh","click","家具城左导航鼠标点击"]);
}if($(this).hasClass("floor-link")){return;}var e=$(this).index();window.scroll(0,c[e]);});}function getGuessLike(){if($("#JS_maylike_ul").length==0){return;
}var b=$.cookie("utag")||"",a="/jiaju/";$.ajax({url:"/solr_api/recommend/listpage/?userTags="+b+"&pageUrl="+a+"&pageSize=20",type:"GET",dataType:"json",success:function(e){if(e&&e.goods&&e.goods.length){var f=$("#JS_maylike_ul li");
var d=[],g;for(var c=0;c<e.goods.length;c++){g=e.goods[c];d='<a href="'+g.goods_uri+'?from=cnxh" target="_blank" title="'+g.new_goods_name+'"><img class="d-img" src="'+$.__IMG+"/"+(g.goods_thumb_2||g.goods_thumb_1)+'" alt="'+g.new_goods_name+'"></a><div class="maylike-item-name"><a href="'+g.goods_uri+'?from=cnxh" target="_blank" title="'+g.new_goods_name+'" class="d-name">'+g.new_goods_name+'</a></div><div class="red maylike-item-prize">&yen;<span data-goods_id="'+g.id+'">'+g.show_price+"</span></div>";
f.get(c).innerHTML=d;}f.each(function(h){var j="";if((h+1)%4==0){j="last4";}if((h+1)%5==0){j+=" last5";}$(this).attr("class",j);});}},complete:function(){$("#JS_maylike_change").click(function(){var d=$("#JS_maylike_ul").height(),c=$("#JS_maylike_ul li").height();
marginTop=parseInt($("#JS_maylike_ul").css("marginTop"));if(d+marginTop-c>0){$("#JS_maylike_ul").css("marginTop",marginTop-c+"px");}else{$("#JS_maylike_ul").css("marginTop",0);
}if(window._ana){window._ana.push(["trackEvent","jjc_cnxh","click","家具城猜你喜欢切换"]);}if(window._gaq){window._gaq.push(["_trackEvent","jjc_cnxh","click","家具城猜你喜欢切换"]);
}});}});}$(window).load(function(){$.lazyImg.start("both");getGuessLike();});$(document).ready(function(){$("img").load(function(){$(this).animate({opacity:"1"},200);
});$(window).resize(function(){var a=document.body.clientWidth;if(a<1460){$("body").removeClass("root-body");}else{if(!$("body").hasClass("root-body")){$("body").addClass("root-body");
}}});stairs_move();if($.saleNumUpdate){$.saleNumUpdate([{selector:".JS_async_price",type:"price",param:"id",key:"show_price",isInt:true}],function(){$(".JS_suit_main").each(function(){var b=$(this).data("goods_id"),a=this.innerHTML-0;
suitGPrice=0;$(".JS_suit_sub_"+b).each(function(d){var c=+$(this).data("goods_num")||1;suitGPrice+=Number(this.innerHTML)*c;});if((suitGPrice-a).toFixed(0)==0){$(".JS_suit_discount_"+b).parent().hide().parents(".suit-prize").addClass("suit-prize-nodis");
}$(".JS_suit_discount_"+b).html((suitGPrice-a).toFixed(0));});});}new AutoPlay();menuEvent();$("#JS_MLL_search_fixed_input").click(function(){historySearch("JS_MLL_search_fixed_input","JS_search_history2");
jQuery.searchKey("JS_MLL_search_fixed_input","JS_search_fixed_suggest","JS_search_history2");$("#JS_MLL_search_fixed_input").unbind("click");$(this).addClass("search-input-focus");
});$("body").on("click",function(b){b=b||window.event;var a=b.target||b.srcElement;if($(a).attr("data-target")!="search"){$("#JS_search_history").hide();
$("#JS_search_history2").hide();}});jQuery(window).on("scroll",function(){var a=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;
if(a>=658){jQuery("#JS_search_fixed_bar").css("top",a+41+"px");jQuery("#JS_menu_map_fix_box").css("top",a+50+"px");jQuery("#Js_aSTotalContainer").addClass("show");
}else{jQuery("#Js_aSTotalContainer").removeClass("show");jQuery("#JS_search_history2").hide();jQuery("#JS_MLL_search_fixed_input").blur();}jQuery("#JS_mll_menu_map_fix").removeClass("menu-map-hover");
});actFloor();initFloors();$.tab($("#JS_tab_nav_colloc li"),$("#JS_tab_body_colloc .tBody"),{lazy:false});$("#JS_tab_nav_colloc li").each(function(){$(this).on("mouseover",function(){if(window._ana){window._ana.push(["trackEvent","jjc_dpzn","click","家具城搭配指南切换"]);
}if(window._gaq){window._gaq.push(["_trackEvent","jjc_dpzn","click","家具城搭配指南切换"]);}});});$("#J-major-list").on("mouseenter","li",function(){var b=$(this).index();
var a=$(this).text();$(this).addClass("current").siblings().removeClass("current");$("#J-major-suit-box").find(".major-suit-con").eq(b).removeClass("none").siblings().addClass("none");
if(window._ana){window._ana.push(["trackEvent","jjc_BrandFurniture","hover",a]);}if(window._gaq){window._gaq.push(["_trackEvent","家具城_大牌家具","hover",a]);
}});$("#J-major-suit-list>li").click(function(){var a=$(this).index();a=parseInt(a)+2;ana_ga_click("产品图"+a);});});function ana_ga_click(a){var b=a=="产品主图"?"产品主图":"产品图";
if(window._ana){window._ana.push(["trackEvent","jjc_BrandFurniture","click",b]);}if(window._gaq){window._gaq.push(["_trackEvent","家具城_大牌家具","click",a]);
}}
/*jinzeze:2017-03-23 17:49:44*/